-- 코드를 입력하세요
SELECT CRCR.CAR_ID AS CAR_ID, CRCR.CAR_TYPE AS CAR_TYPE, ROUND(CRCR.DAILY_FEE*30*(100-CRCDP.DISCOUNT_RATE)/100 ,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CRCR
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP
ON CRCR.CAR_TYPE = CRCDP.CAR_TYPE
WHERE (CRCR.CAR_TYPE = "SUV" OR CRCR.CAR_TYPE = "세단") 
AND (CRCDP.DURATION_TYPE = "30일 이상")
AND (CRCR.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE < '2022-12-01'
    AND END_DATE >= '2022-11-01'))
GROUP BY CAR_ID
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC