SELECT YEAR(SALE.SALES_DATE) AS YEAR, MONTH(SALE.SALES_DATE) AS MONTH, COUNT(DISTINCT SALE.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT SALE.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM USER_INFO AS INFO
    INNER JOIN ONLINE_SALE AS SALE
    ON INFO.USER_ID = SALE.USER_ID AND YEAR(INFO.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC
