SELECT PRO.PRODUCT_ID AS PRODUCT_ID, PRO.PRODUCT_NAME AS PRODUCT_NAME, PRO.PRICE * SUM(ORD.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS PRO 
    INNER JOIN FOOD_ORDER AS ORD 
    ON PRO.PRODUCT_ID = ORD.PRODUCT_ID
WHERE YEAR(ORD.PRODUCE_DATE) = 2022 AND MONTH(ORD.PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC