SELECT EMP.EMP_NO AS EMP_NO, EMP.EMP_NAME AS EMP_NAME, 
CASE WHEN GRA.SCORE >= 96 THEN 'S'
     WHEN GRA.SCORE >= 90 THEN 'A'
     WHEN GRA.SCORE >= 80 THEN 'B'
     ELSE 'C'
END AS GRADE, EMP.SAL * 
CASE WHEN GRA.SCORE >= 96 THEN 0.2
     WHEN GRA.SCORE >= 90 THEN 0.15
     WHEN GRA.SCORE >= 80 THEN 0.1
     ELSE 0
END AS BONUS
FROM HR_EMPLOYEES EMP
    INNER JOIN (SELECT EMP_NO, AVG(SCORE) AS SCORE FROM HR_GRADE GROUP BY EMP_NO) AS GRA
    ON EMP.EMP_NO = GRA.EMP_NO
ORDER BY EMP_NO ASC