SELECT MEM.MEMBER_NAME AS MEMBER_NAME, REV.REVIEW_TEXT AS REVIEW_TEXT, DATE_FORMAT(REV.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS MEM 
INNER JOIN REST_REVIEW AS REV 
    ON MEM.MEMBER_ID = REV.MEMBER_ID
INNER JOIN (
    SELECT MEMBER_ID, COUNT(*) AS CNT 
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
) AS COUNT_REVIEW 
    ON MEM.MEMBER_ID = COUNT_REVIEW.MEMBER_ID
WHERE COUNT_REVIEW.CNT = (
    SELECT COUNT(*) 
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID 
    ORDER BY COUNT(*) DESC 
    LIMIT 1)
ORDER BY REV.REVIEW_DATE ASC, REV.REVIEW_TEXT ASC